'use strict';

enum CardAuthenticationResponse{

    FULLY_AUTHENTICATED = 'FULLY_AUTHENTICATED',
    AUTHENTICATION_NOT_REQUIRED = 'AUTHENTICATION_NOT_REQUIRED',
    NOT_ENROLLED = 'NOT_ENROLLED',
    ENROLLMENT_ERROR = 'ENROLLMENT_ERROR',
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
}

export { CardAuthenticationResponse }
