'use strict';

enum RecurringIndicator{

    REGULAR_TRANSACTION = 'REGULAR_TRANSACTION',
    INITIAL_RECURRING_TRANSACTION = 'INITIAL_RECURRING_TRANSACTION',
    MERCHANT_INITIATED_RECURRING_TRANSACTION = 'MERCHANT_INITIATED_RECURRING_TRANSACTION',
    CUSTOMER_INITIATED_RECURRING_TRANSACTION = 'CUSTOMER_INITIATED_RECURRING_TRANSACTION',
}

export { RecurringIndicator }
