'use strict';

enum RefundType{

    MERCHANT_INITIATED_ONLINE = 'MERCHANT_INITIATED_ONLINE',
    MERCHANT_INITIATED_OFFLINE = 'MERCHANT_INITIATED_OFFLINE',
    CUSTOMER_INITIATED_AUTOMATIC = 'CUSTOMER_INITIATED_AUTOMATIC',
    CUSTOMER_INITIATED_MANUAL = 'CUSTOMER_INITIATED_MANUAL',
}

export { RefundType }
