/* tslint:disable */
/* eslint-disable */
/**
 * Wallee AG TypeScript SDK
 *
 * This library allows to interact with the Wallee AG payment service.
 *
 * Copyright owner: Wallee AG
 * Website: https://en.wallee.com
 * Developer email: ecosystem-team@wallee.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime';
import type { FacadeUserFriendlyQueryStatusModel } from './FacadeUserFriendlyQueryStatusModel';
import {
    FacadeUserFriendlyQueryStatusModelFromJSON,
    FacadeUserFriendlyQueryStatusModelFromJSONTyped,
    FacadeUserFriendlyQueryStatusModelToJSON,
} from './FacadeUserFriendlyQueryStatusModel';

/**
 * 
 * @export
 * @interface SubmittedAnalyticsQueryExecution
 */
export interface SubmittedAnalyticsQueryExecution {
    /**
     * The ID of the target account for which the analytics query will be executed, determining the data scope for the request.
     * @type {number}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly accountId?: number;
    /**
     * The total execution time, in milliseconds, that has been billed for the query.
     * @type {number}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly totalBilledExecutionTimeMs?: number;
    /**
     * The date and time when the query was created.
     * @type {Date}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly createdTimestamp?: Date;
    /**
     * The number of times the query result file has been downloaded.
     * @type {number}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly downloadRequests?: number;
    /**
     * The SQL query as originally submitted by the user.
     * @type {string}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly originalQuery?: string;
    /**
     * The total bytes of data scanned by the submitted query.
     * @type {number}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly scannedBytes?: number;
    /**
     * The unique query token associated with the analytics query execution.
     * @type {string}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly portalQueryToken?: string;
    /**
     * The size, in bytes, of the result file generated by the query.
     * @type {number}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    readonly resultFileBytes?: number;
    /**
     * 
     * @type {FacadeUserFriendlyQueryStatusModel}
     * @memberof SubmittedAnalyticsQueryExecution
     */
    status?: FacadeUserFriendlyQueryStatusModel;
}

/**
 * Check if a given object implements the SubmittedAnalyticsQueryExecution interface.
 */
export function instanceOfSubmittedAnalyticsQueryExecution(value: object): value is SubmittedAnalyticsQueryExecution {
    return true;
}

export function SubmittedAnalyticsQueryExecutionFromJSON(json: any): SubmittedAnalyticsQueryExecution {
    return SubmittedAnalyticsQueryExecutionFromJSONTyped(json, false);
}

export function SubmittedAnalyticsQueryExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmittedAnalyticsQueryExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'totalBilledExecutionTimeMs': json['totalBilledExecutionTimeMs'] == null ? undefined : json['totalBilledExecutionTimeMs'],
        'createdTimestamp': json['createdTimestamp'] == null ? undefined : (new Date(json['createdTimestamp'])),
        'downloadRequests': json['downloadRequests'] == null ? undefined : json['downloadRequests'],
        'originalQuery': json['originalQuery'] == null ? undefined : json['originalQuery'],
        'scannedBytes': json['scannedBytes'] == null ? undefined : json['scannedBytes'],
        'portalQueryToken': json['portalQueryToken'] == null ? undefined : json['portalQueryToken'],
        'resultFileBytes': json['resultFileBytes'] == null ? undefined : json['resultFileBytes'],
        'status': json['status'] == null ? undefined : FacadeUserFriendlyQueryStatusModelFromJSON(json['status']),
    };
}

export function SubmittedAnalyticsQueryExecutionToJSON(value?: Omit<SubmittedAnalyticsQueryExecution, 'accountId'|'totalBilledExecutionTimeMs'|'createdTimestamp'|'downloadRequests'|'originalQuery'|'scannedBytes'|'portalQueryToken'|'resultFileBytes'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': FacadeUserFriendlyQueryStatusModelToJSON(value['status']),
    };
}

