'use strict';

enum SubscriptionState{

    PENDING = 'PENDING',
    INITIALIZING = 'INITIALIZING',
    FAILED = 'FAILED',
    ACTIVE = 'ACTIVE',
    SUSPENDED = 'SUSPENDED',
    TERMINATION_SCHEDULED = 'TERMINATION_SCHEDULED',
    TERMINATING = 'TERMINATING',
    TERMINATED = 'TERMINATED',
}

export { SubscriptionState }
