'use strict';

enum TokenizationMode{

    FORCE_UPDATE = 'FORCE_UPDATE',
    FORCE_CREATION = 'FORCE_CREATION',
    FORCE_CREATION_WITH_ONE_CLICK_PAYMENT = 'FORCE_CREATION_WITH_ONE_CLICK_PAYMENT',
    ALLOW_ONE_CLICK_PAYMENT = 'ALLOW_ONE_CLICK_PAYMENT',
}

export { TokenizationMode }
